language: dart
dart:
  - dev

before_install:
  - sudo apt-get install -y ant

script:
  - ./travis.sh

env:
  - BOT=dart
# TODO(devoncarew): Re-enable this bot:
#   https://github.com/dart-lang/vm_service_drivers/issues/238
#  - BOT=java

branches:
  only:
    - master
