language: java
jdk:
  - oraclejdk8
install: ant deps

before_script:
  - echo Installing Dart...
  - curl https://storage.googleapis.com/dart-archive/channels/dev/release/latest/sdk/dartsdk-linux-x64-release.zip > dart-sdk.zip
  - unzip dart-sdk.zip > /dev/null
  - export PATH="$PATH":`pwd`/dart-sdk/bin

script:
  - ./travis.sh

env:
  - BOT=dart
  - BOT=java

branches:
  only:
    - master
